classname: pipelines.pacwave.pipeline.Pacwave

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*pacwave.spot.30904C.*\.csv

retriever:
  path: pipelines/pacwave/config/retriever.yaml
  
dataset:
  path: pipelines/pacwave/config/dataset.yaml
  overrides: 
    /attrs/dataset_name: spot_30904c
    /attrs/platform_id: SPOT-30904C
    /attrs/geospatial_lat_min: 44.5450
    /attrs/geospatial_lat_max: 44.5841
    /attrs/geospatial_lon_min: -124.2417
    /attrs/geospatial_lon_max: -124.2162

quality:
  path: shared/quality.yaml

storage:
  path: shared/storage.yaml
