classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: tsdat.io.readers.CSVReader
    parameters:
      read_csv_kwargs:
        sep: ", *"
        engine: "python"
        index_col: false
    
coords:
  time:
      name: timestamp
      data_converters:
        - classname: tsdat.io.converters.StringToDatetime
          format: "mixed"
          timezone: UTC

data_vars:
  significantWaveHeight:
    name: significantWaveHeight

  peakPeriod:
    name: peakPeriod
  
  meanPeriod:
    name: meanPeriod
  
  peakDirection:
    name: peakDirection
  
  peakDirectionalSpread:
    name: peakDirectionalSpread

  meanDirection:
    name: meanDirection

  meanDirectionalSpread:
    name: meanDirectionalSpread

  latitude:
    name: latitude

  longitude:
    name: longitude
