attrs:
  title: Spotter API-processed wave statistics
  location_id: pws
  dataset_name: spotter
  data_level: c1
  qualifier: "0401"
  description: " "

  Conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  keywords:
    OCEAN WAVES, GRAVITY WAVES, WIND WAVES
  featureType: timeseries
  summary:
    Wave statistics measured by a Sofar Spotter wave buoy deployed at the PacWave Wave
    Energy Test Site, off the coast of Newport, OR, USA
  id: Spotter
  infoUrl: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl
  standard_name_vocabulary: CF Standard Name Table v84
  # Attribution
  creator_country: USA
  creator_email: ""
  creator_institution: Oregon State University
  creator_institution_url: https://ceoas.oregonstate.edu/
  creator_sector: academic
  creator_type: institution
  creator_url: https://ceoas.oregonstate.edu/
  institution: Oregon State University
  publisher_country: USA
  publisher_email: tsdat@pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL)
  publisher_url: https://www.pnnl.gov/
  acknowledgement: Data efforts funded by US Department of Energy
  platform: buoy
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  platform_id: SPOT-0401
  platform_name: Sofar Spotter Wave Buoy
  geospatial_lat_min: 44.5500
  geospatial_lat_max: 44.5841
  geospatial_lat_units: degree_north
  geospatial_lon_min: -124.2417
  geospatial_lon_max: -124.2163
  geospatial_lon_units: degree_east
  geospatial_vertical_min: 0.0
  geospatial_vertical_max: 0.0
  geospatial_vertical_units: meters
  geospatial_vertical_origin: sea surface
  geospatial_vertical_positive: up
  geospatial_vertical_resolution: 1 m
  source: insitu observations

coords:
  time:
    dims: [time]
    dtype: datetime64[ns]
    attrs:
      long_name: Time
      standard_name: time
      units: seconds since 1970-01-01 00:00:00 UTC
      cf_role: timeseries_id
      coverage_content_type: coordinate
      timezone: UTC

  frequency:
    dims: [frequency]
    dtype: float32
    attrs:
      long_name: Band Center Frequency
      standard_name: wave_frequency
      units: Hz
      coverage_content_type: coordinate

data_vars:
  latitude:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Latitude
      standard_name: latitude
      units: degree_north
      valid_min: -90
      valid_max: 90

  longitude:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Longitude
      standard_name: longitude
      units: degree_east
      valid_min: -180
      valid_max: 180

  # wind_speed:
  #   dims: [time]
  #   dtype: float32
  #   attrs:
  #     long_name: horizontal wind speed
  #     standard_name: wind_speed
  #     units: m/s
  #     comment: "RMSE = 2 m/s for 3 < U10 < 12 m/s, 17% for 10 < U10 < 20 m/s). Estimated from tail of wave energy density spectrum (Voermans et al 2020)."
  #     accuracy: 2

  # wind_direction:
  #   dims: [time]
  #   dtype: float32
  #   attrs:
  #     long_name: wind direction
  #     standard_name: wind_from_direction
  #     units: degree
  #     comment: "RMSE of up to 20 degrees for 10 < U10 < 20 m/s). Estimated from tail of wave energy density spectrum (Voermans et al 2020)."
  #     accuracy: 20

  humidity:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Relative Humidity
      standard_name: relative_humidity
      units: "%"
      coverage_content_type: physicalMeasurement
      valid_min: 0
      valid_max: 100

  air_pressure:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Mean Barometric Pressure
      standard_name: air_pressure
      units: hPa
      coverage_content_type: physicalMeasurement
      valid_min: 800
      valid_max: 1100

  sea_surface_temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Sea Surface Temperature
      standard_name: sea_surface_temperature
      units: degree_C
      coverage_content_type: physicalMeasurement
      valid_min: 0
      valid_max: 40

  significant_wave_height:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Significant Wave Height
      standard_name: sea_surface_wave_significant_height
      units: m
      valid_min: 0
      valid_max: 20

  peak_wave_period:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Peak Wave Period
      standard_name: sea_surface_wave_period_at_variance_spectral_density_maximum
      units: s
      valid_min: 0
      valid_max: 22

  mean_wave_period:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Mean Wave Period
      standard_name: sea_surface_wave_mean_period
      units: s
      valid_min: 0
      valid_max: 22

  peak_wave_direction:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Peak Wave Direction
      standard_name: sea_surface_wave_from_direction_at_variance_spectral_density_maximum
      units: degree
      comment: degrees CW from North
      valid_min: 0
      valid_max: 360

  peak_wave_spread:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Peak Wave Directional Spread
      standard_name: sea_surface_wave_directional_spread_at_variance_spectral_density_maximum
      units: degree
      valid_min: 0
      valid_max: 180

  mean_wave_direction:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Mean Wave Direction
      units: degree
      comment: degrees CW from North
      valid_min: 0
      valid_max: 360

  mean_wave_spread:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Mean Wave Directional Spread
      units: degree
      valid_min: 0
      valid_max: 180

  significant_wave_height_part0:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Significant Wave Height Partition 0
      standard_name: sea_surface_primary_swell_wave_significant_height
      units: m
      valid_min: 0
      valid_max: 20

  mean_wave_period_part0:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Mean Wave Period Partition 0
      standard_name: sea_surface_primary_swell_wave_mean_period
      units: s
      valid_min: 0
      valid_max: 22

  mean_wave_direction_part0:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Mean Wave Direction Partition 0
      standard_name: sea_surface_primary_swell_wave_from_direction
      units: degree
      comment: degrees CW from North
      valid_min: 0
      valid_max: 360

  mean_wave_spread_part0:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Mean Wave Directional spread Partition 0
      standard_name: sea_surface_primary_swell_wave_directional_spread
      units: degree
      valid_min: 0
      valid_max: 180

  start_freq_part0:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Partition 0 Band Start Frequency
      units: Hz

  end_freq_part0:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Partition 0 Band End Frequency
      units: Hz

  significant_wave_height_part1:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Significant Wave Height Partition 1
      standard_name: sea_surface_secondary_swell_wave_significant_height
      units: m
      valid_min: 0
      valid_max: 20

  mean_wave_period_part1:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Mean Wave Period Partition 1
      standard_name: sea_surface_secondary_swell_wave_mean_period
      units: s
      valid_min: 0
      valid_max: 22

  mean_wave_direction_part1:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Mean Wave Direction Partition 1
      standard_name: sea_surface_secondary_swell_wave_from_direction
      units: degree
      comment: degrees CW from North
      valid_min: 0
      valid_max: 360

  mean_wave_spread_part1:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Mean Wave Directional spread Partition 1
      standard_name: sea_surface_secondary_swell_wave_directional_spread
      units: degree
      valid_min: 0
      valid_max: 180

  start_freq_part1:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Partition 1 Band Start Frequency
      units: Hz

  end_freq_part1:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Partition 1 Band End Frequency
      units: Hz

  wave_a1_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: a1 Fourier Coefficient
      units: "1"
      valid_min: -1.0
      valid_max: 1.0

  wave_b1_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: b1 Fourier Coefficient
      units: "1"
      valid_min: -1.0
      valid_max: 1.0

  wave_a2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: a2 Fourier Coefficient
      units: "1"
      valid_min: -1.0
      valid_max: 1.0

  wave_b2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: b2 Fourier Coefficient
      units: "1"
      valid_min: -1.0
      valid_max: 1.0

  wave_energy_density:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: Wave Energy Density
      standard_name: sea_surface_wave_variance_spectral_density
      units: m^2 s
      valid_min: 0.0

  wave_direction:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: Wave Direction
      standard_name: sea_surface_wave_from_direction
      units: degree
      comment: degrees CW from North
      valid_min: 0
      valid_max: 360

  wave_spread:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: Wave Spread
      standard_name: sea_surface_wave_directional_spread
      units: degree
      valid_min: 0
      valid_max: 180
