classname: pipelines.spotter.pipeline.SpotterAPI

triggers:
  - .*\.json

retriever:
  path: pipelines/spotter/config/retriever.yaml

dataset:
  path: pipelines/spotter/config/dataset.yaml

quality:
  path: shared/quality.yaml

storage:
  path: shared/storage.yaml
