attrs:
  title: Raw Spotter Measurements
  description:
    Wave measurements recorded by a Sofar Spotter wave buoy deployed at PacWave, OR
  keywords:
    OCEAN WAVES, GRAVITY WAVES, WIND WAVES
  location_id: pwn
  dataset_name: spotter
  data_level: a1

  Conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  featureType: timeseries
  summary: "see description"
  id: Spotter
  infoUrl: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl.sequim
  standard_name_vocabulary: CF Standard Name Table v84
  # Attribution
  creator_country: USA
  creator_email: ""
  creator_institution: Oregon State University
  creator_institution_url: https://ceoas.oregonstate.edu/
  creator_sector: academic
  creator_type: institution
  creator_url: https://ceoas.oregonstate.edu/
  institution: Oregon State University
  publisher_country: USA
  publisher_email: tsdat@pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL)
  publisher_url: https://www.pnnl.gov/
  acknowledgement: Data efforts funded by US Department of Energy
  comment: Wave statistics data was processed by Spotter bouy
  platform: buoy
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  #platform_id: SPOT-0401
  platform_name: Sofar Spotter Wave Buoy
  geospatial_lat_min: 44.5450
  geospatial_lat_max: 44.5841
  geospatial_lat_units: degree_north
  geospatial_lon_min: -124.2417
  geospatial_lon_max: -124.2162
  geospatial_lon_units: degree_east
  geospatial_vertical_min: 0.0
  geospatial_vertical_max: 0.0
  geospatial_vertical_units: meters
  geospatial_vertical_origin: sea surface
  geospatial_vertical_positive: up
  geospatial_vertical_resolution: 1 m
  source: insitu observations

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      long_name: Time
      standard_name: time
      timezone: UTC

data_vars:
  x:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Surge
      standard_name: platform_surge
      units: m
      valid_min: -8
      valid_max: 8
  y:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Sway
      standard_name: platform_sway
      units: m
      valid_min: -8
      valid_max: 8
  z:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Heave
      standard_name: platform_heave
      units: m
      valid_min: -8
      valid_max: 8
  lat:
    dims: [time]
    dtype: float32
    attrs:
      units: degree_north
      long_name: Latitude
      standard_name: latitude
      valid_min: -90
      valid_max: 90
  lon:
    dims: [time]
    dtype: float32
    attrs:
      units: degree_east
      long_name: Longitude
      standard_name: longitude
      valid_min: -180
      valid_max: 180
  sst:
    dims: [time]
    dtype: float32
    attrs:
      units: degree_C
      long_name: Sea Surface Temperature
      standard_name: sea_surface_temperature
      valid_min: 0
      valid_max: 40
