classname: pipelines.vap_spotter_raw.pipeline.VapSpotterRaw
parameters:
  datastreams:
    - pwn.spotter-pos-400ms.a1
    - pwn.spotter-gps-1min.a1
    - pwn.spotter-sst-1min.a1

triggers: []

retriever:
  path: pipelines/vap_spotter_raw/config/retriever.yaml

dataset:
  path: pipelines/vap_spotter_raw/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
