attrs:
  title: spotter
  description: Wave statistics measured by a Sofar Spotter wave buoy deployed in PacWave South, off the cost of Newport, OR, USA
  location_id: pwn 
  dataset_name: spot_0401
  data_level: c1

  conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  featureType: timeseries
  id: Spotter
  infoURL: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl
  standard_name_vocabulary: CF Standard Name Table v79
  # Attribution
  creator_country: USA
  #creator_email:
  creator_institution: Oregon State University
  creator_institution_url: https://ceoas.oregonstate.edu/
  creator_sector: academic
  creator_type: institution
  creator_url: https://ceoas.oregonstate.edu/
  institution: Oregon State University
  publisher_country: USA
  publisher_email: tsdat@pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL)
  publisher_url: https://www.pnnl.gov/
  acknowledgement: Data efforts funded by US Department of Energy 
  comment: Wave statistics data was processed by Spotter bouy
  platform: buoy
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  platform_id: SPOT-0401
  platform_name: Sofar Spotter Wave Buoy
  geospatial_lat_min: 44.6950
  geospatial_lat_max: 44.6986
  geospatial_lat_units: degrees_north
  geospatial_lon_min: -124.1464
  geospatial_lon_max: -124.1446
  geospatial_lon_units: degrees_east
  geospatial_vertical_min: 0.0
  geospatial_vertical_max: 0.0
  geospatial_vertical_units: meters
  geospatial_vertical_origin: sea surface
  geospatial_vertical_positive: up
  geospatial_vertical_resolution: 1.0
  time_coverage_start: "2023-01-01T00:00:00Z"
  time_coverage_resolution: 00:30:00
  source: insitu observations

coords:
  time:
      dims: [time]
      dtype: datetime64[ns]
      attrs:
        standard_name: time
        units: seconds since 1970-01-01T00:00:00 UTC

data_vars:
  significantWaveHeight:
    dims: [time]
    dtype: double
    attrs:
      standard_name: sea_surface_wave_significant_height
      long_name: Significant Wave Height
      units: m
      valid_min: 0.0
      valid_max: 20.0

  peakPeriod:
    dims: [time]
    dtype: double
    attrs:
      standard_name: sea_surface_wave_period_at_variance_spectral_density_maximum
      long_name: Peak wave period
      units: s
      valid_min: 0.0
      valid_max: 40.0

  meanPeriod:
    dims: [time]
    dtype: double
    attrs:
      standard_name: sea_surface_wave_mean_period
      long_name: Mean wave period
      units: s
      valid_min: 0.0
      valid_max: 40.0

  peakDirection:
    dims: [time]
    dtype: double
    attrs:
      standard_name: sea_surface_wave_from_direction_at_variance_spectral_density_maximum
      long_name: Peak wave direction
      units: degress
      valid_min: 0.0
      valid_max: 360.0

  peakDirectionalSpread:
    dims: [time]
    dtype: double
    attrs: 
      standard_name: sea_surface_wave_directional_spread_at_variance_spectral_density_maximum
      long_name: Peak wave directional spread
      units: degrees
      valid_min: 0.0
      valid_max: 90.0

  meanDirection:
    dims: [time]
    dtype: double
    attrs:
      standard_name: sea_surface_wave_from_direction
      long_name: Mean wave direction
      units: degrees
      valid_min: 0.0
      valid_max: 360.0

  meanDirectionalSpread:
    dims: [time]
    dtype: double
    attrs:
      standard_name: sea_surface_wave_directional_spread
      long_name: Mean wave direcitonal spread
      units: degrees
      valid_min: 0.0
      valid_max: 90.0

  latitude:
    dims: [time]
    dtype: double
    attrs:
      long_name: Latitude
      units: degree_north
      valid_min: -90
      valid_max: 90

  longitude:
    dims: [time]
    dtype: double
    attrs:
      long_name: Longitude
      units: degree_east
      valid_min: -180
      valid_max: 180