classname: pipelines.vap_pacwave.pipeline.VapPacwave
parameters:
  datastreams:
    # DEVELOPER: put your input datastream(s) here. The datastream is the folder name
    # used in the storage area e.g.:
    - pacwave.spot_30904c.c1


triggers: []

retriever:
  path: pipelines/vap_pacwave/config/retriever.yaml

dataset:
  path: pipelines/vap_pacwave/config/dataset.yaml
  overrides: 
    /attrs/dataset_name: spot_30904c
    /attrs/platform_id: SPOT-30904C

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
