classname: tsdat.io.retrievers.StorageRetriever
parameters:
  transformation_parameters:
    
    # Where the point lies in the coordinate bounds (CENTER, LEFT, RIGHT)
    alignment:
      time: CENTER
    
    # How far to look for the next available data point
    range:
      time: 900
    
    # Width of the transformation (only matters for bin averaging)
    width:
      time: 300

coords:
  time:
    name: NA
    data_converters:
      - classname: tsdat.transform.CreateTimeGrid
        interval: 30min

data_vars:
  significantWaveHeight:
    name: significantWaveHeight
    data_converters:
    - classname: tsdat.transform.NearestNeighbor
      coord: time

  peakPeriod:
    name: peakPeriod
    data_converters:
    - classname: tsdat.transform.NearestNeighbor
      coord: time
  
  meanPeriod:
    name: meanPeriod
    data_converters:
    - classname: tsdat.transform.NearestNeighbor
      coord: time
  
  peakDirection:
    name: peakDirection
    data_converters:
    - classname: tsdat.transform.NearestNeighbor
      coord: time
  
  peakDirectionalSpread:
    name: peakDirectionalSpread
    data_converters:
    - classname: tsdat.transform.NearestNeighbor
      coord: time

  meanDirection:
    name: meanDirection
    data_converters:
    - classname: tsdat.transform.NearestNeighbor
      coord: time

  meanDirectionalSpread:
    name: meanDirectionalSpread
    data_converters:
    - classname: tsdat.transform.NearestNeighbor
      coord: time

  latitude:
    name: latitude
    data_converters:
    - classname: tsdat.transform.NearestNeighbor
      coord: time

  longitude:
    name: longitude
    data_converters:
    - classname: tsdat.transform.NearestNeighbor
      coord: time


  # DEVELOPER: Specify the coords/data_vars that should be retrieved
