classname: pipelines.sig250_avgd.pipeline.UpLookingSig250

triggers:
  - .*PWS.*avgd.ad2cp

retriever:
  path: pipelines/sig250_avgd/config/retriever.yaml

dataset:
  path: pipelines/sig250_avgd/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
