attrs:
  title: Spotter GPS measurements
  description:
    GPS position recorded by a Sofar Spotter wave buoy deployed at PacWave, OR.
  location_id: pw_
  dataset_name: spotter
  data_level: a1
  qualifier: gps
  temporal: 1min

  Conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  keywords:
    OCEAN WAVES, GRAVITY WAVES, WIND WAVES
  featureType: timeseries
  summary: "see description"
  id: Spotter
  infoUrl: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl.sequim
  standard_name_vocabulary: CF Standard Name Table v84
  # Attribution
  creator_country: USA
  creator_email: ""
  creator_institution: Oregon State University
  creator_institution_url: https://ceoas.oregonstate.edu/
  creator_sector: academic
  creator_type: institution
  creator_url: https://ceoas.oregonstate.edu/
  institution: Oregon State University
  publisher_country: USA
  publisher_email: tsdat@pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL)
  publisher_url: https://www.pnnl.gov/
  acknowledgement: Data efforts funded by US Department of Energy
  comment: Wave statistics data was processed by Spotter bouy
  platform: buoy
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  # platform_id: SPOT-0401
  platform_name: Sofar Spotter Wave Buoy
  source: insitu observations


coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      long_name: Time
      standard_name: time
      timezone: UTC

data_vars:
  latitude:
    dims: [time]
    dtype: float32
    attrs:
      units: degree_north
      long_name: Latitude
      standard_name: latitude
      valid_min: -90
      valid_max: 90
  longitude:
    dims: [time]
    dtype: float32
    attrs:
      units: degree_east
      long_name: Longitude
      standard_name: longitude
      valid_min: -180
      valid_max: 180
