attrs:
  title: Spotter XYZ measurements
  description:
    Wave statistics measured by a Sofar Spotter wave buoy deployed at PacWave, OR.
  location_id: pwn
  dataset_name: spotter
  data_level: a1
  qualifier: pos
  temporal: 400ms
  fs: 2.5

  Conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  keywords:
    OCEAN WAVES, GRAVITY WAVES, WIND WAVES
  featureType: timeseries
  summary: "see description"
  id: Spotter
  infoUrl: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl.sequim
  standard_name_vocabulary: CF Standard Name Table v84
  # Attribution
  creator_country: USA
  creator_email: ""
  creator_institution: Oregon State University
  creator_institution_url: https://ceoas.oregonstate.edu/
  creator_sector: academic
  creator_type: institution
  creator_url: https://ceoas.oregonstate.edu/
  institution: Oregon State University
  publisher_country: USA
  publisher_email: tsdat@pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL)
  publisher_url: https://www.pnnl.gov/
  acknowledgement: Data efforts funded by US Department of Energy
  comment: Wave statistics data was processed by Spotter bouy
  platform: buoy
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  # platform_id: SPOT-0401
  platform_name: Sofar Spotter Wave Buoy
  geospatial_lat_min: 44.5450
  geospatial_lat_max: 44.5841
  geospatial_lat_units: degree_north
  geospatial_lon_min: -124.2417
  geospatial_lon_max: -124.2162
  geospatial_lon_units: degree_east
  geospatial_vertical_min: 0.0
  geospatial_vertical_max: 0.0
  geospatial_vertical_units: meters
  geospatial_vertical_origin: sea surface
  geospatial_vertical_positive: up
  geospatial_vertical_resolution: 1 m
  source: insitu observations

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      long_name: Time
      standard_name: time
      timezone: UTC

data_vars:
  x:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Surge
      standard_name: platform_surge
      units: m
      valid_min: -3
      valid_max: 3
  y:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Sway
      standard_name: platform_sway
      units: m
      valid_min: -3
      valid_max: 3
  z:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Heave
      standard_name: platform_heave
      units: m
      valid_min: -3
      valid_max: 3
