classname: pipelines.spotter_raw.pipeline.Waves

triggers:
  - .*FLT.CSV

retriever:
  path: pipelines/spotter_raw/config/retriever.yaml

dataset:
  path: pipelines/spotter_raw/config/dataset_flt.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
