classname: pipelines.spotter_raw.pipeline.SpotterRaw

triggers:
  - .*30857.*\.zip

retriever:
  path: pipelines/spotter_raw/config/retriever.yaml

dataset:
  path: pipelines/spotter_raw/config/dataset.yaml
  overrides:
    /attrs/location_id: 30857

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
