classname: tsdat.io.retrievers.DefaultRetriever
parameters:
  merge_kwargs:
    join: "outer"
readers:
  .*\.zip:
    classname: tsdat.io.readers.ZipReader
    parameters:
      readers:
        .*FLT.*:
          classname: pipelines.spotter_raw.readers.FLTReader
        .*LOC.*:
          classname: pipelines.spotter_raw.readers.GPSReader
        .*SST.*:
          classname: pipelines.spotter_raw.readers.SpotterRawReader
          parameters:
            time_var: "time_sst"
        .*BARO.*:
          classname: pipelines.spotter_raw.readers.SpotterRawReader
          parameters:
            time_var: "time_baro"
        .*HTU.*:
          classname: pipelines.spotter_raw.readers.SpotterRawReader
          parameters:
            time_var: "time_met"
      exclude: [.*PWR.*, .*SPC.*, .*SYS.*, .*GMN.*, .*HDR.*, .*ERR.*, .*\.log, .*dashboard.*, .*download.*]

coords:
  time:
    .*FLT.*:
      name: time
      data_converters:
        - classname: pipelines.spotter_raw.converters.EpochTimeConverter
  time_gps:
    .*LOC.*:
      name: time_gps
      data_converters:
        - classname: pipelines.spotter_raw.converters.EpochTimeConverter
  time_sst:
    .*SST.*:
      name: time_sst
      data_converters:
        - classname: pipelines.spotter_raw.converters.EpochTimeConverter
  time_met:
    .*HTU.*:
      name: time_met
      data_converters:
        - classname: pipelines.spotter_raw.converters.EpochTimeConverter
  time_baro:
    .*BARO.*:
      name: time_baro
      data_converters:
        - classname: pipelines.spotter_raw.converters.EpochTimeConverter
  time_pwr:
    .*PWR.*:
      name: time_pwr
      data_converters:
        - classname: pipelines.spotter_raw.converters.EpochTimeConverter


data_vars:
  x:
    .*FLT.*:
      name: x
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: mm
  y:
    .*FLT.*:
      name: y
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: mm
  z:
    .*FLT.*:
      name: z
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: mm
  latitude:
    .*LOC.*:
      name: lat
  longitude:
    .*LOC.*:
      name: lon
  sea_surface_temperature: 
    .*SST.*: 
      name: temperature (C)
  air_pressure: 
    .*BARO.*: 
      name: pressure (mbar)
      data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: mbar
  air_temperature:
    .*HTU.*: 
      name: temperature (C)
  humidity: 
    .*HTU.*: 
      name: humidity (%RH)
