classname: tsdat.io.retrievers.DefaultRetriever
parameters:
  merge_kwargs:
    join: "outer"
readers:
  .*\.nc:
    classname: pipelines.spotter_raw.readers.NetCDFReader

coords:
  time:
    name: flt_time
  time_gps:
    name: loc_time
  time_sst:
    name: sst_time
  time_met:
    name: htu_time
  time_baro:
    name: baro_time

data_vars:
  x:
    name: flt_outx_mm
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: mm
  y:
    name: flt_outy_mm
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: mm
  z:
    name: flt_outz_mm
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: mm
  latitude:
    name: loc_lat_deg
  lat_min:
    name: loc_lat_min_1e5
  longitude:
    name: loc_long_deg
  lon_min:
    name: loc_long_min_1e5
  sea_surface_temperature: 
    name: sst_temperature_c
  air_pressure: 
    name: baro_pressure_mbar
    data_converters:
    - classname: tsdat.io.converters.UnitsConverter
      input_units: mbar
  air_temperature:
    name: htu_temperature_c
  humidity: 
    name: htu_humidity_rh
