classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*.json:
    classname: pipelines.nexsens.readers.NexsensJsonReader

coords:
  time:
    name: time

data_vars:
  latitude:
    name: [Latitude, "125989"]
  longitude:
    name: [Longitude, "125990"]
  altitude:
    name: [Altitude, "125991"]
  heading:
    name: [Heading, "125992"]
  significant_wave_height:
    name: [Hs Wave Height, "125993"]
  peak_wave_period:
    name: [Tp (DPD) Wave Period, "125994"]
  peak_wave_direction:
    name: [Dominant Wave Direction, "125995"]
  mean_wave_direction:
    name: [Mean Wave Direction (MWD), "125996"]
  max_wave_height:
    name: [Hmax Wave Height, "125997"]
  h10_wave_height:
    name: [H10 Wave Height, "125998"]
  sample_number:
    name: [Sample No, "125999"] 
