classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*.dat:
    classname: pipelines.floatr_adcp.readers.CampbellRDIReader

coords:
  time:
    name: time
  range:
    name: range

data_vars:
  vel_east:
    name: vel_east
  vel_north:
    name: vel_north