attrs:
  title: PacWave FLOATr ADCP data
  description:
    Data collected by a down-looking ADCP deployed in a FLOATr buoy at PacWave
  location_id: pws
  dataset_name: floatr_adcp_raw
  data_level: a1
  qualifier: "001"

  Conventions: CF-1.6, ACDD-1.3, IOOS-1.2
  keywords: pacwave, water velocity, water direction
  featureType: timeSeries
  summary: "see description"
  id: adcp
  naming_authority: gov.pnnl
  infoUrl: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  standard_name_vocabulary: CF Standard Name Table v84  # Attribution
  creator_country: USA
  creator_email: ""
  creator_institution: Oregon State University
  creator_institution_url: https://ceoas.oregonstate.edu/
  creator_sector: academic
  creator_type: institution
  creator_url: https://ceoas.oregonstate.edu/
  institution: Oregon State University
  publisher_country: USA
  publisher_email: tsdat@pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL)
  publisher_url: https://www.pnnl.gov/
  acknowledgement: Data efforts funded by US Department of Energy
  platform: buoy
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  # platform_id:
  platform_name: FLOATr
  instrument: In Situ/Laboratory Instruments > Current/Wind Meters > Current Meters
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Teledyne RDI Workhorse 300 kHz
  geospatial_lat_min: 44.5500
  geospatial_lat_max: 44.5841
  geospatial_lat_units: degree_north
  geospatial_lon_min: -124.2417
  geospatial_lon_max: -124.2163
  geospatial_lon_units: degree_east
  geospatial_vertical_min: 0.0
  geospatial_vertical_max: 0.0
  geospatial_vertical_units: meters
  geospatial_vertical_origin: sea surface
  geospatial_vertical_positive: up
  geospatial_vertical_resolution: 1 m
  source: insitu observations


coords:
  time:
    dims: [time]
    dtype: datetime64[ns]
    attrs:
      long_name: Time
      standard_name: time
      units: Seconds since 1970-01-01 00:00:00 UTC
      cf_role: timeseries_id
      coverage_content_type: coordinate
      timezone: UTC # is this correct?

  range:
    dims: [range]
    dtype: float32
    attrs:
      coverage_content_type: coordinate
      units: m
      long_name: Profile Range
      description: Distance to the center of each depth bin

  beam:
    dims: [beam]
    dtype: int
    attrs:
      units: "1"
      long_name: Beam Reference Frame
      coverage_content_type: coordinate

  dir:
    dims: [dir]
    dtype: str
    attrs:
      units: "1"
      long_name: Reference Frame
      coverage_content_type: coordinate
      ref_frame: earth

data_vars:
  number:
    dims: [time]
    dtype: int
    attrs:
      units: "1"
      long_name: Ensemble Number
      standard_name: number_of_observations

  builtin_test_fail:
    dims: [time]
    dtype: int
    attrs:
      units: "1"
      long_name: Built-In Test Failures

  c_sound:
    dims: [time]
    dtype: float32
    attrs:
      units: m s-1
      long_name: Speed of Sound
      standard_name: speed_of_sound_in_sea_water

  depth:
    dims: [time]
    dtype: float32
    attrs:
      units: m
      long_name: Depth
      standard_name: depth

  pitch:
    dims: [time]
    dtype: float32
    attrs:
      units: degree
      long_name: Pitch
      standard_name: platform_pitch

  roll:
    dims: [time]
    dtype: float32
    attrs:
      units: degree
      long_name: Roll
      standard_name: platform_roll

  heading:
    dims: [time]
    dtype: float32
    attrs:
      units: degree
      long_name: Heading
      standard_name: platform_orientation

  temp:
    dims: [time]
    dtype: float32
    attrs:
      units: degree_C
      coverage_content_type: physicalMeasurement
      long_name: Temperature
      standard_name: sea_water_temperature

  salinity:
    dims: [time]
    dtype: float32
    attrs:
      units: psu
      long_name: Salinity
      standard_name: sea_water_salinity

  heading_std:
    dims: [time]
    dtype: float32
    attrs:
      units: degree
      long_name: Heading Standard Deviation

  pitch_std:
    dims: [time]
    dtype: float32
    attrs:
      units: degree
      long_name: Pitch Standard Deviation

  roll_std:
    dims: [time]
    dtype: float32
    attrs:
      units: degree
      long_name: Roll Standard Deviation

  pressure:
    dims: [time]
    dtype: float32
    attrs:
      units: dbar
      long_name: Pressure
      standard_name: sea_water_pressure

  pressure_std:
    dims: [time]
    dtype: float32
    attrs:
      units: dbar
      long_name: Pressure Standard Deviation

  vel:
    dims: [time, range, dir]
    dtype: float32
    attrs:
      units: m s-1
      coverage_content_type: physicalMeasurement
      long_name: Water Velocity
      valid_min: -2
      valid_max: 2

  amp:
    dims: [time, range, beam]
    dtype: int
    attrs:
      units: "1"
      coverage_content_type: physicalMeasurement
      long_name: Acoustic Signal Amplitude
      standard_name: signal_intensity_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water

  corr:
    dims: [time, range, beam]
    dtype: int
    attrs:
      units: "1"
      coverage_content_type: physicalMeasurement
      long_name: Acoustic Signal Correlation
      standard_name: beam_consistency_indicator_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water

  prcnt_gd:
    dims: [time, range, beam]
    dtype: int
    attrs:
      units: "%"
      coverage_content_type: physicalMeasurement
      long_name: Percent Good
      standard_name: proportion_of_acceptable_signal_returns_from_acoustic_instrument_in_sea_water
