classname: pipelines.floatr_adcp_raw.pipeline.FLOATrADCPRaw

triggers:
  - .*PWN.*003.*\.000
  - .*PWN.*003.*\.PD0

retriever:
  path: pipelines/floatr_adcp_raw/config/retriever.yaml

dataset:
  path: pipelines/floatr_adcp_raw/config/dataset.yaml
  overrides:
    /attrs/location_id: pwn
    /attrs/qualifier: "003"
    /attrs/geospatial_lat_min: 44.6812
    /attrs/geospatial_lat_max: 44.6986
    /attrs/geospatial_lon_min: -124.1462
    /attrs/geospatial_lon_max: -124.1218

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
