classname: pipelines.floatr_adcp_raw.pipeline.FLOATrADCPRaw

triggers:
  - .*PWS.*007.*\.000
  - .*PWS.*007.*\.PD0

retriever:
  path: pipelines/floatr_adcp_raw/config/retriever.yaml

dataset:
  path: pipelines/floatr_adcp_raw/config/dataset.yaml
  overrides:
    /attrs/qualifier: "007"

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
