classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.floatr_adcp_raw.readers.RDIReader
    parameters:
      adcp_depth: 1.5
      correlation_filter_threshold: 30

coords:
  time:
    name: time
  range:
    name: range
  beam:
    name: beam
  dir:
    name: dir

data_vars:
  vel:
    name: vel
  amp:
    name: amp
  corr:
    name: corr
  prcnt_gd:
    name: prcnt_gd
  speed_of_sound:
    name: c_sound
  depth:
    name: depth
  temperature:
    name: temp
  salinity:
    name: salinity
  pressure:
    name: pressure
  pitch:
    name: pitch
  roll:
    name: roll
  heading:
    name: heading
