attrs:
  title: PacWave FLOATr Met data
  location_id: pws
  dataset_name: floatr_met
  data_level: a1
  qualifier: "001"
  description: " "

  summary: Meteorological sensors connected to a Campbell Scientific CR1000X
    datalogger installed on a FLOATr buoy at PacWave measuring sea surface parameters
  keywords: PACWAVE, METEOROLOGICAL, WINDSPEED, AIR TEMPERATURE, AIR PRESSURE
  Conventions: CF-1.6, ACDD-1.3, IOOS-1.2
  featureType: timeSeries
  id: met
  naming_authority: gov.pnnl
  infoUrl: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  standard_name_vocabulary: CF Standard Name Table v84  # Attribution
  creator_country: USA
  creator_email: ""
  creator_institution: Oregon State University
  creator_institution_url: https://ceoas.oregonstate.edu/
  creator_sector: academic
  creator_type: institution
  creator_url: https://ceoas.oregonstate.edu/
  institution: Oregon State University
  publisher_country: USA
  publisher_email: tsdat@pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL)
  publisher_url: https://www.pnnl.gov/
  acknowledgement: Data efforts funded by US Department of Energy
  platform: buoy
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  # platform_id:
  platform_name: FLOATr
  instrument: In Situ/Laboratory Instruments > Current/Wind Meters > Wind Monitor
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Campbell CR1000X
  geospatial_lat_min: 44.5500
  geospatial_lat_max: 44.5841
  geospatial_lat_units: degree_north
  geospatial_lon_min: -124.2417
  geospatial_lon_max: -124.2163
  geospatial_lon_units: degree_east
  geospatial_vertical_min: 0.0
  geospatial_vertical_max: 0.0
  geospatial_vertical_units: meters
  geospatial_vertical_origin: sea surface
  geospatial_vertical_positive: up
  geospatial_vertical_resolution: 1 m
  source: insitu observations


coords:
  time:
    dims: [time]
    dtype: datetime64[ns]
    attrs:
      long_name: Time
      standard_name: time
      units: Seconds since 1970-01-01 00:00:00 UTC
      timezone: UTC 

data_vars:
  latitude:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Latitude
      units: degree
      valid_min: 30
      valid_max: 60
  longitude:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Longitude
      units: degree
      valid_min: -150
      valid_max: -110
  air_temperature:
    dims: [time]
    dtype: float32
    attrs: 
      standard_name: air_temperature
      long_name: Average Air Temperature
      units: degree_C
      valid_min: 0
      valid_max: 40
      valid_delta: 10
  air_pressure:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: air_pressure
      long_name: Average Barometric Pressure
      units: millibar
      valid_min: 850
      valid_max: 1100
  raw_shortwave_rad_1:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Average Raw Shortwave Radiation 1
      units: "1"
  shortwave_rad_1:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: net_downward_shortwave_flux_in_air
      long_name: Average Shortwave Radiation 1
      units: W/m^2
      valid_min: 0
      valid_max: 2000
  raw_shortwave_rad_2:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Average Raw Shortwave Radiation 2
      units: "1"
  shortwave_rad_2:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: net_downward_shortwave_flux_in_air
      long_name: Average Shortwave Radiation 2
      units: W/m^2
      valid_min: 0
      valid_max: 2000
  wind_vel_east:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: eastward_wind
      long_name: Average Eastward Wind Component
      units: m/s
      valid_min: -70
      valid_max: 70
  wind_vel_north:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: northward_wind
      long_name: Average Northward Wind Component
      units: m/s
      valid_min: -70
      valid_max: 70
  windspeed:
    dims: [time]
    dtype: float32
    attrs: 
      standard_name: wind_speed
      long_name: Average Wind Speed
      units: m/s
      valid_min: -70
      valid_max: 70
  windspeed_std:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Standard Deviation of Wind Speed
      units: m/s
  wind_dir_true:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: wind_from_direction
      long_name: True Wind Direction  
      units: m/s
      valid_min: 0
      valid_max: 360
  wind_dir_relative:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Relative Wind Direction
      units: m/s
      valid_min: 0
      valid_max: 360
  wind_dir_stationary:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Stationary Wind Direction
      units: m/s
      valid_min: 0
      valid_max: 360
  buoy_heading:
    dims: [time]
    dtype: float32
    attrs: 
      standard_name: platform_heading
      long_name: Buoy Heading
      units: degree
