attrs:
  title: PacWave FLOATr Met data
  description:
    Data collected by CTD in a FLOATr buoy at PacWave
  location_id: pws
  dataset_name: met
  data_level: a1
  qualifier: "001"

  Conventions: CF-1.6, ACDD-1.3, IOOS-1.2
  keywords: pacwave, water velocity, water direction
  featureType: timeSeries
  summary: "see description"
  id: adcp
  naming_authority: gov.pnnl
  infoUrl: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  standard_name_vocabulary: CF Standard Name Table v84  # Attribution
  creator_country: USA
  creator_email: ""
  creator_institution: Oregon State University
  creator_institution_url: https://ceoas.oregonstate.edu/
  creator_sector: academic
  creator_type: institution
  creator_url: https://ceoas.oregonstate.edu/
  institution: Oregon State University
  publisher_country: USA
  publisher_email: tsdat@pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL)
  publisher_url: https://www.pnnl.gov/
  acknowledgement: Data efforts funded by US Department of Energy
  platform: buoy
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  # platform_id:
  platform_name: FLOATr
  instrument: Campbell Data Logger
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Campbell CR1000X
  geospatial_lat_min: 44.5450
  geospatial_lat_max: 44.5841
  geospatial_lat_units: degree_north
  geospatial_lon_min: -124.2417
  geospatial_lon_max: -124.2162
  geospatial_lon_units: degree_east
  geospatial_vertical_min: 0.0
  geospatial_vertical_max: 0.0
  geospatial_vertical_units: meters
  geospatial_vertical_origin: sea surface
  geospatial_vertical_positive: up
  geospatial_vertical_resolution: 1 m
  source: insitu observations


coords:
  time:
    dims: [time]
    dtype: datetime64[ns]
    attrs:
      long_name: Time
      standard_name: time
      units: Seconds since 1970-01-01 00:00:00 UTC
      timezone: UTC 

data_vars:
  latitude:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Latitude
      units: degree_north
      valid_min: -90
      valid_max: 90
  longitude:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Longitude
      units: degree_east
      valid_min: -180
      valid_max: 180
  AirTC_Avg:
    dims: [time]
    dtype: float32
    attrs: 
      standard_name: air_temperature
      long_name: Average Air Temperature
      units: degree_C
  BP_mbar_Avg:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: air_pressure
      long_name: Average Barometric Pressure
      units: millibar
  Rad1Raw_Avg:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Average Raw Shortwave Radiation 1
      units: "1"
  Rad1_Avg:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: net_downward_shortwave_flux_in_air
      long_name: Average Shortwave Radiation 1
      units: W/m^2
  Rad2Raw_Avg:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Average Raw Shortwave Radiation 2
      units: "1"
  Rad2_Avg:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Average Shortwave Radiation 2
      units: W/m^2
  U_Wnd_Avg:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: eastward_wind
      long_name: Average Eastward Wind Component
      units: m/s
  V_Wnd_Avg:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: northward_wind
      long_name: Average Northward Wind Component
      units: m/s
  WS_ms_Avg:
    dims: [time]
    dtype: float32
    attrs: 
      standard_name: wind_speed
      long_name: Average Wind Speed
      units: m/s
  WS_ms_Std:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Standard Deviation of Wind Speed
      units: m/s
  True_WindDir:
    dims: [time]
    dtype: float32
    attrs:
      standard_name: wind_from_direction
      long_name: True Wind Direction  
      units: m/s
  Wdir_rel:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Relative Wind Direction
      units: m/s
  Wdir_stationary:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Stationary Wind Direction
      units: m/s
  heading:
    dims: [time]
    dtype: float32
    attrs: 
      standard_name: platform_heading
      long_name: Buoy Heading
      units: degree

