classname: pipelines.floatr_met.pipeline.FLOATrMET

triggers:
  - .*PWS.*004.*Met.*\.dat

retriever:
  path: pipelines/floatr_met/config/retriever.yaml

dataset:
  path: pipelines/floatr_met/config/dataset.yaml
  overrides:
    /attrs/qualifier: "004"

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
