classname: pipelines.floatr_met.pipeline.FLOATrMET

triggers:
  - .*PWS.*005.*Met.*\.dat
  - .*5S.*Met.*\.csv

retriever:
  path: pipelines/floatr_met/config/retriever.yaml

dataset:
  path: pipelines/floatr_met/config/dataset.yaml
  overrides:
    /attrs/qualifier: "005"

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
