classname: pipelines.floatr_met.pipeline.FLOATrMET

triggers:
  - .*PWS.*Met.*\.dat

retriever:
  path: pipelines/floatr_met/config/retriever.yaml

dataset:
  path: pipelines/floatr_met/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
