classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.floatr_met.readers.CampbellMetReader

coords:
  time:
    name: time

data_vars:
  latitude:
    name: GPSlat
  longitude:
    name: GPSlon
  air_temperature:
    name: AirTC_Avg
  air_pressure:
    name: BP_mbar_Avg
    data_converters:
    - classname: tsdat.io.converters.UnitsConverter
      input_units: mbar
  raw_shortwave_rad_1:
    name: Rad1Raw_Avg
  shortwave_rad_1:
    name: Rad1_Avg
  raw_shortwave_rad_2:
    name: Rad2Raw_Avg
  shortwave_rad_2:
    name: Rad2_Avg
  wind_vel_east:
    name: U_Wnd_Avg
  wind_vel_north:
    name: V_Wnd_Avg
  windspeed:
    name: WS_ms_Avg
  windspeed_std:
    name: WS_ms_Std
  wind_dir_true:
    name: True_WindDir
  wind_dir_relative:
    name: Wdir_rel
  wind_dir_stationary:
    name: Wdir_stationary
  buoy_heading:
    name: heading
