classname: pipelines.sig250.pipeline.UpLookingSig250

triggers:
  - .*S104922.*PWS.*\d{2}.nc
  - .*s104922.*pws.*\d{2}.nc

retriever:
  path: pipelines/sig250/config/retriever.yaml

dataset:
  path: pipelines/sig250/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
