classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.sig250.readers.Sig250Reader
    parameters:
      depth_offset: 0.5
      salinity: 35
      pressure_offset: -0.7
      correlation_filter_threshold: 30
      ast_quality_threshold: 40
      le_quality_threshold: 45

coords:
  time:
    name: time
  time_avg:
    name: time_avg
  range:
    name: range
  range_avg:
    name: range_avg
  dir:
    name: dir
  dirIMU:
    name: dirIMU
  beam:
    name: beam
  inst:
    name: inst
  earth:
    name: earth
  x1:
    name: x1
  x2:
    name: x2

data_vars:
  # Near-surface velocity for wave direction estimations
  vel:
    name: vel
  amp:
    name: amp
  corr:
    name: corr
  orientmat:
    name: orientmat
  beam2inst_orientmat:
    name: beam2inst_orientmat
  speed_of_sound:
    name: c_sound
  pressure:
    name: pressure
  temperature:
    name: temp
  depth:
    name: depth
  heading:
    name: heading
  pitch:
    name: pitch
  roll:
    name: roll
  accel:
    name: accel 
  mag: 
    name: mag

  # Surface distance measurements for waves
  pressure_alt:
    name: pressure_alt
  le_dist_alt:
    name: le_dist_alt
  le_quality_alt:
    name: le_quality_alt
  ast_dist_alt:
    name: ast_dist_alt
  ast_quality_alt:
    name: ast_quality_alt
  ast_offset_time_alt:
    name: ast_offset_time_alt
  
  # Averaged velocity
  vel_avg:
    name: vel_avg
  amp_avg:
    name: amp_avg
  corr_avg:
    name: corr_avg
  speed: 
    name: U_mag
  direction:
    name: U_dir
  orientmat_avg:
    name: orientmat_avg
  speed_of_sound_avg:
    name: c_sound_avg
  pressure_avg:
    name: pressure_avg
  temperature_avg:
    name: temp_avg
  depth_avg:
    name: depth_avg
  heading_avg:
    name: heading_avg
  pitch_avg:
    name: pitch_avg
  roll_avg:
    name: roll_avg
  accel_avg:
    name: accel_avg
  mag_avg: 
    name: mag_avg