attrs:
  title: PacWave FLOATr CTD data
  location_id: pws
  dataset_name: floatr_ctd
  data_level: a1
  qualifier: "001"
  description: " "

  Conventions: CF-1.6, ACDD-1.3, IOOS-1.2
  keywords: pacwave, seawater, temperature, pressure, salinity, conductivity, dissolved oxygen
  featureType: timeSeries
  summary:  Seabird SBE 37-SM MicroCAT CTD (conductivity temperature depth) sensor installed
    on a FLOATr buoy at PacWave measuring sea surface parameters.
  id: met
  naming_authority: gov.pnnl
  infoUrl: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  standard_name_vocabulary: CF Standard Name Table v84  # Attribution
  creator_country: USA
  creator_email: ""
  creator_institution: Oregon State University
  creator_institution_url: https://ceoas.oregonstate.edu/
  creator_sector: academic
  creator_type: institution
  creator_url: https://ceoas.oregonstate.edu/
  institution: Oregon State University
  publisher_country: USA
  publisher_email: tsdat@pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL)
  publisher_url: https://www.pnnl.gov/
  acknowledgement: Data efforts funded by US Department of Energy
  platform: buoy
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  # platform_id:
  platform_name: FLOATr
  instrument:
    In Situ/Laboratory Instruments > Conductivity Sensors > Conductivity Meters
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Seabird SBE 37-SM MicroCAT
  geospatial_lat_min: 44.5500
  geospatial_lat_max: 44.5841
  geospatial_lat_units: degree_north
  geospatial_lon_min: -124.2417
  geospatial_lon_max: -124.2163
  geospatial_lon_units: degree_east
  geospatial_vertical_min: 0.0
  geospatial_vertical_max: 0.0
  geospatial_vertical_units: meters
  geospatial_vertical_origin: sea surface
  geospatial_vertical_positive: up
  geospatial_vertical_resolution: 1 m
  source: insitu observations


coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      long_name: Time
      standard_name: time
      units: seconds since 1970-01-01 00:00:00 UTC
      cf_role: timeseries_id
      coverage_content_type: coordinate
      timezone: UTC

data_vars:
  temp:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Water Temperature (degC)
      standard_name: sea_water_temperature
      units: degree_C
      coverage_content_type: physicalMeasurement
      valid_min: 0
      valid_max: 25
      valid_delta: 5
  do:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Dissolved Oxygen (mg/L)
      standard_name: mass_concentration_of_oxygen_in_sea_water
      units: mg L-1
      coverage_content_type: physicalMeasurement
      valid_min: 0
      valid_max: 30
      valid_delta: 2
  conductivity:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Conductivity (S/m)
      standard_name: sea_water_electrical_conductivity
      units: S/m
      coverage_content_type: physicalMeasurement
  salinity:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Salinity (psu)
      standard_name: sea_water_practical_salinity
      units: psu
      coverage_content_type: physicalMeasurement
      description: >-
        Practical Salinity is a determination of the salinity of sea water, based on its
        electrical conductance. The measured conductance, corrected for temperature and
        pressure, is compared to the conductance of a standard potassium chloride
        solution, producing a value on the Practical Salinity Scale of 1978.
      valid_min: 25
      valid_max: 40
      valid_delta: 0.5
