classname: pipelines.floatr_ctd.pipeline.FLOATrCTD

triggers:
  - .*PWS.*04.*Ocean.*\.dat
  - .*4S.*Ocean.*\.csv

retriever:
  path: pipelines/floatr_ctd/config/retriever.yaml
  overrides: 
    /readers/.*/classname: pipelines.floatr_ctd.readers.SeabirdCTDReaderV2

dataset:
  path: pipelines/floatr_ctd/config/dataset.yaml
  overrides:
    /attrs/qualifier: "004"

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
