classname: pipelines.floatr_ctd.pipeline.FLOATrCTD

triggers:
  - .*PWS.*Ocean.*\.dat

retriever:
  path: pipelines/floatr_ctd/config/retriever.yaml

dataset:
  path: pipelines/floatr_ctd/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
