classname: pipelines.floatr_ctd.pipeline.FLOATrCTD

triggers:
  - .*PWS.*003.*Ocean.*\.dat
  - .*3S.*Ocean.*\.csv

retriever:
  path: pipelines/floatr_ctd/config/retriever.yaml

dataset:
  path: pipelines/floatr_ctd/config/dataset.yaml
  overrides:
    /attrs/qualifier: "003"

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
