classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.floatr_ctd.readers.SeabirdCTDReader

coords:
  time:
    name: time

data_vars:
  water_temperature:
    name: temp
  # dissolved_oxygen:
  #   name: do
  conductivity: 
    name: conductivity
  salinity:
    name: salinity
