classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*\.zip:
    classname: tsdat.io.readers.ZipReader
    parameters:
      readers:
        .*FLT.*:
          classname: tsdat.io.readers.CSVReader
          parameters:
            read_csv_kwargs:
              index_col: "time"
              names: ["ms", "time", "x", "y", "z", ""]
              header: 0
              on_bad_lines: "skip"
              na_values: ["millis", "GPS_Epoch_Time(s)", "outx(mm)", "outy(mm)", "outz(mm)"]
              
        .*LOC.*:
          classname: pipelines.spotter_raw_old.readers.GPSReader
        .*SST.*:
          classname: pipelines.spotter_raw_old.readers.SSTReader
      exclude: [.*SPC.*, .*SYS.*, .*GMN.*, .*HDR.*, .*ERR.*, .*BARO.*, .*HTU.*, .*PWR.*, .*\.log,]

coords:
  time:
    .*FLT.*:
      name: time
      data_converters:
        - classname: pipelines.spotter_raw_old.converters.EpochTimeConverter
  time_aux:
    .*LOC.*:
      name: time
      data_converters:
        - classname: pipelines.spotter_raw_old.converters.EpochTimeConverter
    .*SST.*:
      name: time
      data_converters:
        - classname: pipelines.spotter_raw_old.converters.EpochTimeConverter

data_vars:
  x:
    .*FLT.*:
      name: x
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: mm
  y:
    .*FLT.*:
      name: y
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: mm
  z:
    .*FLT.*:
      name: z
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: mm
  latitude:
    .*LOC.*:
      name: lat
  longitude:
    .*LOC.*:
      name: lon
  sea_surface_temperature: 
    .*SST.*: 
      name: temperature (C)
