classname: pipelines.vap_spotter.pipeline.VapSpotterApi
parameters:
  datastreams:
    - pwn.spotter-30903C.c1

triggers: []

retriever:
  path: pipelines/vap_spotter/config/retriever.yaml

dataset:
  path: pipelines/vap_spotter/config/dataset.yaml
  overrides: 
    /attrs/location_id: pwn
    /attrs/qualifier: "30903C"
    /attrs/platform_id: SPOT-30903C

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
